Use the right Twig date filter
Because while running `assetic:dump` command I always have:

```
The template "SyliusResourceBundle::layout.html.twig" contains an
error: Unknown "format_date" filter. Did you mean "format_file" in
"SyliusResourceBundle::layout.html.twig" at line 50
```